# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auroraplot_dataviewer.ui'
#
# Created: Wed Jun 22 14:43:42 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 714)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/dataviewer_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtGui.QSplitter(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.dataLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.dataLayout.setContentsMargins(0, 0, 0, 0)
        self.dataLayout.setObjectName("dataLayout")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtGui.QToolBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(400, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.datetimePage = QtGui.QWidget()
        self.datetimePage.setGeometry(QtCore.QRect(0, 0, 400, 434))
        self.datetimePage.setObjectName("datetimePage")
        self.gridLayout_2 = QtGui.QGridLayout(self.datetimePage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.datetimePage)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 1, 1, 1)
        self.durationUnitsBox = QtGui.QComboBox(self.datetimePage)
        self.durationUnitsBox.setObjectName("durationUnitsBox")
        self.gridLayout_2.addWidget(self.durationUnitsBox, 4, 3, 1, 1)
        self.calendarWidget = QtGui.QCalendarWidget(self.datetimePage)
        self.calendarWidget.setMinimumSize(QtCore.QSize(280, 250))
        self.calendarWidget.setMaximumSize(QtCore.QSize(280, 280))
        self.calendarWidget.setMouseTracking(False)
        self.calendarWidget.setMinimumDate(QtCore.QDate(1752, 9, 15))
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setHorizontalHeaderFormat(QtGui.QCalendarWidget.SingleLetterDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_2.addWidget(self.calendarWidget, 1, 1, 1, 3)
        self.starttimeWidget = QtGui.QTimeEdit(self.datetimePage)
        self.starttimeWidget.setTimeSpec(QtCore.Qt.UTC)
        self.starttimeWidget.setObjectName("starttimeWidget")
        self.gridLayout_2.addWidget(self.starttimeWidget, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.datetimePage)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.datetimePage)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 3, 1, 1)
        self.durationBox = QtGui.QSpinBox(self.datetimePage)
        self.durationBox.setObjectName("durationBox")
        self.gridLayout_2.addWidget(self.durationBox, 4, 2, 1, 1)
        self.widget = QtGui.QWidget(self.datetimePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 6, 2, 1, 1)
        self.widget_2 = QtGui.QWidget(self.datetimePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 4, 1, 1)
        self.toolBox.addItem(self.datetimePage, "")
        self.datasetPage = QtGui.QWidget()
        self.datasetPage.setGeometry(QtCore.QRect(0, 0, 262, 329))
        self.datasetPage.setObjectName("datasetPage")
        self.gridLayout = QtGui.QGridLayout(self.datasetPage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtGui.QLabel(self.datasetPage)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.datasetPage)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.line = QtGui.QFrame(self.datasetPage)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 0, 1, 3)
        self.label_8 = QtGui.QLabel(self.datasetPage)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.addPlotButton = QtGui.QPushButton(self.datasetPage)
        self.addPlotButton.setObjectName("addPlotButton")
        self.gridLayout.addWidget(self.addPlotButton, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.datasetPage)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 9, 0, 1, 1)
        self.projectBox = QtGui.QComboBox(self.datasetPage)
        self.projectBox.setObjectName("projectBox")
        self.gridLayout.addWidget(self.projectBox, 6, 1, 1, 2)
        self.siteBox = QtGui.QComboBox(self.datasetPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.siteBox.sizePolicy().hasHeightForWidth())
        self.siteBox.setSizePolicy(sizePolicy)
        self.siteBox.setObjectName("siteBox")
        self.gridLayout.addWidget(self.siteBox, 7, 1, 1, 2)
        self.channelsLineEdit = QtGui.QLineEdit(self.datasetPage)
        self.channelsLineEdit.setObjectName("channelsLineEdit")
        self.gridLayout.addWidget(self.channelsLineEdit, 9, 1, 1, 1)
        self.dataTypeBox = QtGui.QComboBox(self.datasetPage)
        self.dataTypeBox.setObjectName("dataTypeBox")
        self.gridLayout.addWidget(self.dataTypeBox, 0, 1, 1, 1)
        self.removeDatasetButton = QtGui.QPushButton(self.datasetPage)
        self.removeDatasetButton.setObjectName("removeDatasetButton")
        self.gridLayout.addWidget(self.removeDatasetButton, 2, 2, 1, 1)
        self.plotsTreeWidget = QtGui.QTreeWidget(self.datasetPage)
        self.plotsTreeWidget.setObjectName("plotsTreeWidget")
        self.plotsTreeWidget.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.plotsTreeWidget, 1, 0, 1, 3)
        self.archiveBox = QtGui.QComboBox(self.datasetPage)
        self.archiveBox.setObjectName("archiveBox")
        self.gridLayout.addWidget(self.archiveBox, 8, 1, 1, 2)
        self.label_9 = QtGui.QLabel(self.datasetPage)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.addDatasetButton = QtGui.QPushButton(self.datasetPage)
        self.addDatasetButton.setObjectName("addDatasetButton")
        self.gridLayout.addWidget(self.addDatasetButton, 9, 2, 1, 1)
        self.toolBox.addItem(self.datasetPage, "")
        self.optionsPage = QtGui.QWidget()
        self.optionsPage.setGeometry(QtCore.QRect(0, 0, 96, 26))
        self.optionsPage.setObjectName("optionsPage")
        self.optionsLayout = QtGui.QGridLayout(self.optionsPage)
        self.optionsLayout.setObjectName("optionsLayout")
        self.toolBox.addItem(self.optionsPage, "")
        self.logPage = QtGui.QWidget()
        self.logPage.setGeometry(QtCore.QRect(0, 0, 188, 128))
        self.logPage.setObjectName("logPage")
        self.gridLayout_3 = QtGui.QGridLayout(self.logPage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.logTextEdit = QtGui.QPlainTextEdit(self.logPage)
        self.logTextEdit.setObjectName("logTextEdit")
        self.gridLayout_3.addWidget(self.logTextEdit, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logClearButton = QtGui.QPushButton(self.logPage)
        self.logClearButton.setObjectName("logClearButton")
        self.horizontalLayout_2.addWidget(self.logClearButton)
        self.logSaveButton = QtGui.QPushButton(self.logPage)
        self.logSaveButton.setObjectName("logSaveButton")
        self.horizontalLayout_2.addWidget(self.logSaveButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.toolBox.addItem(self.logPage, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.progressBar = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.commandBox = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandBox.sizePolicy().hasHeightForWidth())
        self.commandBox.setSizePolicy(sizePolicy)
        self.commandBox.setMinimumSize(QtCore.QSize(400, 100))
        self.commandBox.setMaximumSize(QtCore.QSize(1000, 100))
        self.commandBox.setCheckable(False)
        self.commandBox.setObjectName("commandBox")
        self.goButton = QtGui.QPushButton(self.commandBox)
        self.goButton.setGeometry(QtCore.QRect(10, 10, 61, 51))
        self.goButton.setObjectName("goButton")
        self.autoUpdateCheckBox = QtGui.QCheckBox(self.commandBox)
        self.autoUpdateCheckBox.setGeometry(QtCore.QRect(10, 70, 151, 22))
        self.autoUpdateCheckBox.setObjectName("autoUpdateCheckBox")
        self.toolbarFrame = QtGui.QFrame(self.commandBox)
        self.toolbarFrame.setGeometry(QtCore.QRect(70, 10, 331, 51))
        self.toolbarFrame.setObjectName("toolbarFrame")
        self.toolbarLayout = QtGui.QHBoxLayout(self.toolbarFrame)
        self.toolbarLayout.setObjectName("toolbarLayout")
        self.helpButton = QtGui.QPushButton(self.commandBox)
        self.helpButton.setGeometry(QtCore.QRect(300, 60, 91, 31))
        self.helpButton.setObjectName("helpButton")
        self.verticalLayout.addWidget(self.commandBox)
        self.gridLayout_4.addWidget(self.splitter_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label.setBuddy(self.starttimeWidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Aurora Plot - Data Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Start Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.starttimeWidget.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Duration:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "UTC", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.datetimePage), QtGui.QApplication.translate("MainWindow", "Date and time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Site:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Plot type:", None, QtGui.QApplication.UnicodeUTF8))
        self.addPlotButton.setText(QtGui.QApplication.translate("MainWindow", "Add new plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Channels:", None, QtGui.QApplication.UnicodeUTF8))
        self.channelsLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "eg. 3-7,9,12 or H,Z", None, QtGui.QApplication.UnicodeUTF8))
        self.removeDatasetButton.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Archive:", None, QtGui.QApplication.UnicodeUTF8))
        self.addDatasetButton.setText(QtGui.QApplication.translate("MainWindow", "Add data set", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.datasetPage), QtGui.QApplication.translate("MainWindow", "Data sets", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.optionsPage), QtGui.QApplication.translate("MainWindow", "Plotting options", None, QtGui.QApplication.UnicodeUTF8))
        self.logClearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear log", None, QtGui.QApplication.UnicodeUTF8))
        self.logSaveButton.setText(QtGui.QApplication.translate("MainWindow", "Save log", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.logPage), QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.goButton.setText(QtGui.QApplication.translate("MainWindow", "Draw", None, QtGui.QApplication.UnicodeUTF8))
        self.autoUpdateCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Real-time updating", None, QtGui.QApplication.UnicodeUTF8))
        self.helpButton.setText(QtGui.QApplication.translate("MainWindow", "Show help", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
